const products = [
  {
    subCategory: "664d21f92a8f9e001c50a1a1",
    name: "Çikolatalı Cruffin",
    price: 45,
    description: "İçinde erimiş Belçika çikolatası olan taptaze cruffin.",
    ingredients: ["Un", "Yumurta", "Çikolata", "Tereyağı"],
    calories: 320,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isSpicy: false,
    allergens: ["Yumurta", "Gluten"],
    availability: true,
    image: "/info1.png",
  },
  {
    subCategory: "664d21f92a8f9u9hvrjh890r389hue001c50a1a2",
    name: "Vegan Smoothie",
    price: 60,
    description:
      "Muz, yaban mersini ve badem sütüyle hazırlanan taptaze smoothie.",
    ingredients: ["Muz", "Yaban mersini", "Badem sütü"],
    calories: 180,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isSpicy: false,
    allergens: ["Kuruyemiş"],
    availability: true,
    image: "/info2.png",
  },
  {
    subCategory: "664d21f92a9hurh97r8f9e001c50a1a3",
    name: "Kahvaltı Tabağı",
    price: 95,
    description:
      "Peynir, zeytin, domates, bal ve ekmekten oluşan klasik Türk kahvaltısı.",
    ingredients: ["Peynir", "Zeytin", "Bal", "Domates", "Ekmek"],
    calories: 550,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isSpicy: false,
    allergens: ["Laktoz", "Gluten"],
    availability: true,
    image: "/info3.png",
  },
  {
    subCategory: "664d21f92a8f9e0ij0rgjureh8y7901c50a1a4",
    name: "Acılı Tavuk Wrap",
    price: 75,
    description: "Acı soslu tavuk, yeşillik ve özel sos ile sarılmış lavaş.",
    ingredients: ["Tavuk", "Acı sos", "Lavaş", "Marul", "Mayonez"],
    calories: 470,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: false,
    isSpicy: true,
    allergens: ["Gluten", "Yumurta"],
    availability: true,
    image: "/info4.png",
  },
  {
    subCategory: "664d2iu34i0431f9265jj23evca8f9e001c50a1a5",
    name: "Glutensiz Havuçlu Kek",
    price: 50,
    description: "Badem unu ile yapılmış, tarçınlı ve havuçlu yumuşak kek.",
    ingredients: ["Havuç", "Tarçın", "Badem unu", "Yumurta"],
    calories: 280,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isSpicy: false,
    allergens: ["Yumurta", "Kuruyemiş"],
    availability: true,
    image: "/bg_patis.png",
  },

  {
    subCategory: "664d21f92reniocri430ij3g48f9e001c50a1a1",
    name: "Çikolatalı Cruffin",
    price: 45,
    description: "İçinde erimiş Belçika çikolatası olan taptaze cruffin.",
    ingredients: ["Un", "Yumurta", "Çikolata", "Tereyağı"],
    calories: 320,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isSpicy: false,
    allergens: ["Yumurta", "Gluten"],
    availability: true,
    image: "/info1.png",
  },
  {
    subCategory: "664d21feiucriifg45g42a8f9e001c50a1a2",
    name: "Vegan Smoothie",
    price: 60,
    description:
      "Muz, yaban mersini ve badem sütüyle hazırlanan taptaze smoothie.",
    ingredients: ["Muz", "Yaban mersini", "Badem sütü"],
    calories: 180,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isSpicy: false,
    allergens: ["Kuruyemiş"],
    availability: true,
    image: "/info2.png",
  },
  {
    subCategory: "664d21f92noin43iia8r3443tf9e001c50a1a3",
    name: "Kahvaltı Tabağı",
    price: 95,
    description:
      "Peynir, zeytin, domates, bal ve ekmekten oluşan klasik Türk kahvaltısı.",
    ingredients: ["Peynir", "Zeytin", "Bal", "Domates", "Ekmek"],
    calories: 550,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isSpicy: false,
    allergens: ["Laktoz", "Gluten"],
    availability: true,
    image: "/info3.png",
  },
  {
    subCategory: "664d21f92aj43i040j8fsdfsdf50a1a4",
    name: "Acılı Tavuk Wrap",
    price: 75,
    description: "Acı soslu tavuk, yeşillik ve özel sos ile sarılmış lavaş.",
    ingredients: ["Tavuk", "Acı sos", "Lavaş", "Marul", "Mayonez"],
    calories: 470,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: false,
    isSpicy: true,
    allergens: ["Gluten", "Yumurta"],
    availability: true,
    image: "/info4.png",
  },
  {
    subCategory: "664d21fi0cr0j40j492a8f9e001c50a1a5",
    name: "Glutensiz Havuçlu Kek",
    price: 50,
    description: "Badem unu ile yapılmış, tarçınlı ve havuçlu yumuşak kek.",
    ingredients: ["Havuç", "Tarçın", "Badem unu", "Yumurta"],
    calories: 280,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isSpicy: false,
    allergens: ["Yumurta", "Kuruyemiş"],
    availability: true,
    image: "/bg_patis.png",
  },
  {
    subCategory: "664d21f92a8fnjocriori9e001c50a1a1",
    name: "Çikolatalı Cruffin",
    price: 45,
    description: "İçinde erimiş Belçika çikolatası olan taptaze cruffin.",
    ingredients: ["Un", "Yumurta", "Çikolata", "Tereyağı"],
    calories: 320,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isSpicy: false,
    allergens: ["Yumurta", "Gluten"],
    availability: true,
    image: "/info1.png",
  },
  {
    subCategory: "664d21f92a8f9e0jno3on401c50a1a2",
    name: "Vegan Smoothie",
    price: 60,
    description:
      "Muz, yaban mersini ve badem sütüyle hazırlanan taptaze smoothie.",
    ingredients: ["Muz", "Yaban mersini", "Badem sütü"],
    calories: 180,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isSpicy: false,
    allergens: ["Kuruyemiş"],
    availability: true,
    image: "/info2.png",
  },
  {
    subCategory: "664d21f92a8f99uh348734fe001c50a1a3",
    name: "Kahvaltı Tabağı",
    price: 95,
    description:
      "Peynir, zeytin, domates, bal ve ekmekten oluşan klasik Türk kahvaltısı.",
    ingredients: ["Peynir", "Zeytin", "Bal", "Domates", "Ekmek"],
    calories: 550,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isSpicy: false,
    allergens: ["Laktoz", "Gluten"],
    availability: true,
    image: "/info3.png",
  },
  {
    subCategory: "664d21f92a8f9egerg35ge001c50a1a4",
    name: "Acılı Tavuk Wrap",
    price: 75,
    description: "Acı soslu tavuk, yeşillik ve özel sos ile sarılmış lavaş.",
    ingredients: ["Tavuk", "Acı sos", "Lavaş", "Marul", "Mayonez"],
    calories: 470,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: false,
    isSpicy: true,
    allergens: ["Gluten", "Yumurta"],
    availability: true,
    image: "/info4.png",
  },
  {
    subCategory: "664d21f9265jj234234ger23evca8f9e001c50a1a5",
    name: "Glutensiz Havuçlu Kek",
    price: 50,
    description: "Badem unu ile yapılmış, tarçınlı ve havuçlu yumuşak kek.",
    ingredients: ["Havuç", "Tarçın", "Badem unu", "Yumurta"],
    calories: 280,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isSpicy: false,
    allergens: ["Yumurta", "Kuruyemiş"],
    availability: true,
    image: "/bg_patis.png",
  },

  {
    subCategory: "664d21f92re3434342g48f9e001c50a1a1",
    name: "Çikolatalı Cruffin",
    price: 45,
    description: "İçinde erimiş Belçika çikolatası olan taptaze cruffin.",
    ingredients: ["Un", "Yumurta", "Çikolata", "Tereyağı"],
    calories: 320,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isSpicy: false,
    allergens: ["Yumurta", "Gluten"],
    availability: true,
    image: "/info1.png",
  },
  {
    subCategory: "664d21fef5656g45g42a8f9e001c50a1a2",
    name: "Vegan Smoothie",
    price: 60,
    description:
      "Muz, yaban mersini ve badem sütüyle hazırlanan taptaze smoothie.",
    ingredients: ["Muz", "Yaban mersini", "Badem sütü"],
    calories: 180,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isSpicy: false,
    allergens: ["Kuruyemiş"],
    availability: true,
    image: "/info2.png",
  },
  {
    subCategory: "664d21f92a8r34533443tf9e001c50a1a3",
    name: "Kahvaltı Tabağı",
    price: 95,
    description:
      "Peynir, zeytin, domates, bal ve ekmekten oluşan klasik Türk kahvaltısı.",
    ingredients: ["Peynir", "Zeytin", "Bal", "Domates", "Ekmek"],
    calories: 550,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isSpicy: false,
    allergens: ["Laktoz", "Gluten"],
    availability: true,
    image: "/info3.png",
  },
  {
    subCategory: "664d21f92a8122121fsdfsdf50a1a4",
    name: "Acılı Tavuk Wrap",
    price: 75,
    description: "Acı soslu tavuk, yeşillik ve özel sos ile sarılmış lavaş.",
    ingredients: ["Tavuk", "Acı sos", "Lavaş", "Marul", "Mayonez"],
    calories: 470,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: false,
    isSpicy: true,
    allergens: ["Gluten", "Yumurta"],
    availability: true,
    image: "/info4.png",
  },
  {
    subCategory: "664d21f232392a8f9e001c50a1a5",
    name: "Glutensiz Havuçlu Kek",
    price: 50,
    description: "Badem unu ile yapılmış, tarçınlı ve havuçlu yumuşak kek.",
    ingredients: ["Havuç", "Tarçın", "Badem unu", "Yumurta"],
    calories: 280,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isSpicy: false,
    allergens: ["Yumurta", "Kuruyemiş"],
    availability: true,
    image: "/bg_patis.png",
  },
];

export default products;
